# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-27 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_formchoice_answer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='formchoice',
            name='subjectID',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50),
        ),
    ]
